spring:
  application:
    name: Istanbul Coders Test Containers
  rabbitmq:
      host: 127.0.0.1
      username: guest
      password: guest
      virtual-host: /
      listener:
            simple:
              concurrency: 5
              max-concurrency: 30
              retry:
                enabled: true
                initial-interval: 1000ms
                multiplier: 2
                max-attempts: 5
mq:
  user:
    update:
      exchange-name: istanbulcoders.user.api.user.changed.events
      queue-name: istanbulcoders.user.api.user.changed.events
      dead-letter-queue-name: istanbulcoders.user.api.user.changed.dead-letter
      args:
        x-dead-letter-exchange:
        x-dead-letter-routing-key: ${mq.user.update.dead-letter-queue-name}